dist: trusty
sudo: false

branches:
  except:
  - /^dependabot\/.*$/

language: python

python:
  - 2.7

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

    # Percy secrets are included here to enable Percy's GitHub integration
    # on community-submitted PRs
    - PERCY_PROJECT=skylines/skylines
    - PERCY_TOKEN=81bf0245987c87eb4924eae0b085cb60596f2f0f4d4ffe27e171828535aa6812

addons:
  chrome: stable
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3

services:
  - postgresql
  - redis

cache:
  pip: true
  yarn: true

before_install:
  - pip install pipenv

  - nvm install 10
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower

install:
  - pipenv install --dev

  - cd ember
  - yarn install
  - bower install
  - cd ..

before_script:
  # Create the testing database
  - psql -U postgres -c 'CREATE DATABASE skylines_test;'

  # Install PostGIS extension into the database
  - psql -U postgres -d skylines_test -c 'CREATE EXTENSION postgis;'

  # Install fuzzystrmatch extension into the database
  - psql -U postgres -d skylines_test -c 'CREATE EXTENSION fuzzystrmatch;'

script:
  # Run the test suite
  - pipenv run py.test -vv --color=yes --cov=skylines --cov-report term-missing:skip-covered

  - cd ember
  - yarn test
